# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 003a146fbf5cd3110691441a2846240a1a5eb9f2e1be963c2a7fca037a3e2d4fdfea588a6d0b75792680cda67581eab0ad6ea6a3c18ce673192802f0433eabfe

test:
  secret_key_base: 91eb8c80888cd2035ff9caf995a14e75b9ccebd68583cd24e8eae0c8ce98263ad99e6186527331449be4297a7a0afbcdb11061db08a091b1c66b433c22dd0b8e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
